### ISSUE TITLE
Multiple USB source script is not working

### ISSUE THREAD

**Issue by Ajithbalakrishnan** [socieboy/deepstream-examples#1]
Hi Frank,
Thanks for the repo. I Itried to run the Multiple  USB source script using my 2 USB cameras. Its not showing any error. But  its not showing any output and not fetching camera data.  Mean while GPU usage is also zero. (Cameras are still off stage) I am attaching the terminal log here. Please help us to resolve it.

Thanks,
AB
![Screenshot from 2021-03-15 00-02-51](https://user-images.githubusercontent.com/32813021/111080619-48682100-8525-11eb-9c30-0fee14bff8de.png)

**Comment by prakhar154** [comment]
Hi @Ajithbalakrishnan, did you resolve this issue?

**Comment by Ajithbalakrishnan** [comment]
I didn't spend time on it. I created my own version. Please try this below repo if u r facing any error.
https://github.com/Ajithbalakrishnan/Deepstream-Python-Samples

**Comment by socieboy** [comment]
Hello everyone, sorry for the late response, i just update the code using the new plugin of nvidia, i have tested and is working, i just tested for 1 camera, but it should work for multiple, just make sure you update the list of sources. the tiler is configured to show 4 blocks.

https://github.com/socieboy/deepstream-examples/blob/master/Multi-Camera/usb-display.py

**Comment by Ajithbalakrishnan** [comment]
Hey, Its working now. But Sycript still shows some bugs.  I am using a Logitech C270 USB camera. 
Pls checck the below result for the bugs. I checked with other codes, camera works fine with other scripts.
![Screenshot from 2021-06-24 02-13-21](https://user-images.githubusercontent.com/32813021/123165596-0fc7d400-d492-11eb-8264-780fe3b60c65.png)

**Comment by socieboy** [comment]
@Ajithbalakrishnan  the screenshot you share doesn't show any ERRORS or WARNINGS... 
Can you share a full log?
