### ISSUE TITLE
Stream camera using webRTC, Gstreamer still doesn't have fully support for this.

### ISSUE THREAD

**Issue by HoangTienDuc** [socieboy/deepstream-examples#3]
Hi @socieboy . Your work is so awesome.
I am new in webrtc in gstreamer.
I have a question, how webRTC in gstreamer can help us to stream camera? 
What is pros and cons?
Hope to get your experiences.

**Comment by socieboy** [comment]
Hello @HoangTienDuc, WebRTC is the new standard to transfer video and data over the web, plus is the fast way, if you can you should use it. regarding Gstreamer and WebRTC, the webrtcbin plugin is considered under the bad plugins, and it's not fully developed yet. it's missing one important thing to complete the handshake of the connections between clients. I was not able to complete my example due this problem.
More information is on the the Gstreamer officia repository

https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1174#note_1040400

**Comment by HoangTienDuc** [comment]
Thank you very much
